### ISSUE TITLE
pip install -e . --> error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by gorjious** [BlackFoundryCom/fontra#127]
While running `pip install -e .` I get the following error:

```
(fontra) Gors-MacBook-Pro:fontra-main gorjious$ pip install -e .
Obtaining file:///Users/gorjious/Desktop/fontra-main
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      Traceback (most recent call last):
        File "/Users/gorjious/Desktop/fontra-main/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/gorjious/Desktop/fontra-main/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/gorjious/Desktop/fontra-main/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 445, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 280, in __init__
          self.finalize_options()
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 123, in infer_version
          _assign_version(dist, config)
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools_scm/integration.py", line 62, in _assign_version
          _version_missing(config)
        File "/private/var/folders/nh/s33w4gy51c71rsy1z5ty40w80000gn/T/pip-build-env-ievdc1c_/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 109, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /Users/gorjious/Desktop/fontra-main.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by anthrotype** [comment]
I think you didn't use git to clone the repository but probably downloaded a source tarball from Github?
You need to do `git clone https://github.com/BlackFoundryCom/fontra` to download the git repository, then `cd fontra` to move inside the downloaded directory and then you can do `pip install -e .`

**Comment by anthrotype** [comment]
setuptools-scm can't work out the version string from the git metadata if the directory is not a git repository (the tarball generated by Github do not contain a .git subfolder, they only contain the source files without the git metadata)

**Comment by justvanrossum** [comment]
Hmm, would leaving out the `-e` flag help? It's a bit sad it doesn't work from a zip download.

**Comment by anthrotype** [comment]
it's a known limitation of setuptools-scm. Try exporting `SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0` or whatever is the current version (there's no tags anyway yet)

**Comment by gorjious** [comment]
git clone works. thanks!

**Comment by anthrotype** [comment]
I think setuptools-scm now supports git archives if you follow these instructions (haven't tried myself): https://github.com/pypa/setuptools_scm#git-archives

**Comment by anthrotype** [comment]
ok, it works. I just did that for nanoemoji and can now install from a github zip download:
https://github.com/googlefonts/nanoemoji/commit/2ffdd23faad153c5cec763b6e210befc9d704cd1

I suggest we do the same for all the packages which use setuptools-scm like Fontra so users that don't want to clone the git repository can simply pip install directly from the zip (whether unpacked or not, pip can unzip automatically).

**Comment by anthrotype** [comment]
this works at any commit, not just tagged releases. nice!

**Comment by justvanrossum** [comment]
I'm not sure I want to add more boilerplate files to the repo just for this case. I want to upload to PyPI soon (#109), which would have prevented this issue also.
